import React from "react";
import { NavLink } from "react-router-dom";
import { Bot, Building2, FilePlus, FolderClock, Inbox, LayoutDashboard, MessageSquareText } from "lucide-react";
import { EVRAGBrand } from "./EVRAGBrand";
import type { UserRole } from "../types/case";
import { navigationForRole } from "../utils/roleNavigation";
interface Props { role: UserRole; onOpenCopilot?: () => void }
const icons: Record<string, React.ComponentType<{ size?: number }>> = { home: LayoutDashboard, incoming: Inbox, clarification: FolderClock, routing: Inbox, history: FolderClock, assigned: Inbox, progress: FolderClock, approval: FolderClock, deadline: FolderClock };
export const Sidebar: React.FC<Props> = ({ role, onOpenCopilot }) => <aside className="sidebar no-print"><div className="sidebar-brand"><EVRAGBrand variant="full" theme="light"/></div><nav className="sidebar-nav"><span className="sidebar-section-label">ÇALIŞMA ALANI</span>{navigationForRole(role).map((item) => { const Icon = icons[item.key] || Inbox; return <NavLink key={item.key} to={item.to} end={item.to === "/"} className={({ isActive }) => `sidebar-link ${isActive ? "sidebar-link-active" : ""}`}><Icon size={19}/><span>{item.text}</span></NavLink>; })}<span className="sidebar-section-label">ARAÇLAR</span>{role === "EVRAK_KAYIT" && <NavLink to="/yeni-evrak" className={({ isActive }) => `sidebar-link ${isActive ? "sidebar-link-active" : ""}`}><FilePlus size={19}/><span>Demo Evrak Girişi</span></NavLink>}<NavLink to="/kurum-rehberi" className={({ isActive }) => `sidebar-link ${isActive ? "sidebar-link-active" : ""}`}><Building2 size={19}/><span>Kurum Rehberi</span></NavLink><button type="button" className="sidebar-link sidebar-copilot-link" onClick={onOpenCopilot}><MessageSquareText size={19}/><span>EVRAG Copilot</span></button>{role === "EVRAK_KAYIT" && <NavLink to="/ai-operasyon" className={({ isActive }) => `sidebar-link ${isActive ? "sidebar-link-active" : ""}`}><Bot size={19}/><span>AI Operasyonları</span></NavLink>}</nav><div className="sidebar-footer"><div className="sidebar-footer-text"><span className="sidebar-health-dot"/>Kurumsal çalışma alanı</div><div className="sidebar-runtime">AI destekler · Personel karar verir</div></div></aside>;
