import React, { useEffect, useState } from "react";
import { Building2, ChevronRight, LogOut, UserRound } from "lucide-react";
import { useLocation } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";
import { demoApi, type DemoPersona } from "../services/demoApi";
import type { CurrentUser } from "../types/case";
import { roleLabel } from "../utils/roleNavigation";
const titles: Record<string, string> = { "/": "Ana Sayfa", "/dosyalar": "Dosyalar", "/gecmis": "İşlem Geçmişi", "/yeni-evrak": "Demo Evrak Girişi", "/kurum-rehberi": "Kurum Rehberi", "/ai-operasyon": "AI Operasyonları" };
export function TopBar({ user }: { user: CurrentUser }) { const { logout, login } = useAuth(); const [personas, setPersonas] = useState<DemoPersona[]>([]); const location = useLocation(); useEffect(() => { void demoApi.personas().then((x) => setPersonas(x.items)).catch(() => setPersonas([])); }, []); const title = location.pathname.startsWith("/dosya/") ? "Dosya Çalışma Alanı" : location.pathname.startsWith("/evrak/") ? "AI Analiz İncelemesi" : titles[location.pathname] || "EVRAG"; return <header className="top-bar no-print"><div className="top-bar-breadcrumb"><Building2 size={16}/><span>EVRAG</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="demo-role-switch"><small>YARIŞMA DEMOSU</small><label>Demo Rolünü Değiştir<select value={personas.find((p) => p.name === user.name)?.user_key || ""} onChange={(event) => void login(event.target.value)}>{personas.map((p) => <option value={p.user_key} key={p.user_key}>{p.name} · {p.institution_id === "belediye" ? "Belediye" : "Kaymakamlık"}</option>)}</select></label></div><div className="current-user"><span className="current-user-icon"><UserRound/></span><div><strong>{user.name}</strong><small>{user.department_name || user.department_code} · {roleLabel(user.role)}</small></div><button onClick={logout} title="Güvenli çıkış"><LogOut/><span>Çıkış</span></button></div></header>; }
