"""Canonical Case workflow enums from docs/CASE_WORKFLOW_CONTRACT.md."""

from __future__ import annotations

ROLE_EVRAK_KAYIT = "EVRAK_KAYIT"
ROLE_BIRIM_PERSONELI = "BIRIM_PERSONELI"
INTERNAL_ROLES = frozenset({ROLE_EVRAK_KAYIT, ROLE_BIRIM_PERSONELI})

SOURCE_TYPES = frozenset({"VATANDAS", "DIS_KURUM", "KURUM_ICI"})
SOURCE_CHANNELS = frozenset(
    {"WEB_FORM", "FIZIKI_EVRAK", "EPOSTA", "KEP", "EBYS", "KURUM_ICI"}
)
ORIGINATOR_TYPES = frozenset({"VATANDAS", "DIS_KURUM", "KURUM_ICI"})

STATUS_RECEIVED = "RECEIVED"
STATUS_ANALYZING = "ANALYZING"
STATUS_WAITING_INITIAL_REVIEW = "WAITING_INITIAL_REVIEW"
STATUS_WAITING_CITIZEN_INFO = "WAITING_CITIZEN_INFO"
STATUS_READY_TO_ROUTE = "READY_TO_ROUTE"
STATUS_IN_DEPARTMENT = "IN_DEPARTMENT"
STATUS_IN_PROGRESS = "IN_PROGRESS"
STATUS_RESPONSE_DRAFTED = "RESPONSE_DRAFTED"
STATUS_WAITING_FINAL_APPROVAL = "WAITING_FINAL_APPROVAL"
STATUS_COMPLETED = "COMPLETED"
STATUS_CLOSED = "CLOSED"

DURABLE_STATUSES = frozenset(
    {
        STATUS_RECEIVED,
        STATUS_ANALYZING,
        STATUS_WAITING_INITIAL_REVIEW,
        STATUS_WAITING_CITIZEN_INFO,
        STATUS_READY_TO_ROUTE,
        STATUS_IN_DEPARTMENT,
        STATUS_IN_PROGRESS,
        STATUS_RESPONSE_DRAFTED,
        STATUS_WAITING_FINAL_APPROVAL,
        STATUS_COMPLETED,
        STATUS_CLOSED,
    }
)

REGISTRY_INBOX_STATUSES = frozenset(
    {
        STATUS_RECEIVED,
        STATUS_ANALYZING,
        STATUS_WAITING_INITIAL_REVIEW,
        STATUS_WAITING_CITIZEN_INFO,
        STATUS_READY_TO_ROUTE,
        STATUS_COMPLETED,
    }
)

DEPARTMENT_INBOX_STATUSES = frozenset(
    {
        STATUS_IN_DEPARTMENT,
        STATUS_IN_PROGRESS,
        STATUS_RESPONSE_DRAFTED,
        STATUS_WAITING_FINAL_APPROVAL,
        STATUS_COMPLETED,
    }
)

EVENT_CASE_RECEIVED = "CASE_RECEIVED"
EVENT_ANALYSIS_STARTED = "ANALYSIS_STARTED"
EVENT_ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
EVENT_CITIZEN_INFO_REQUESTED = "CITIZEN_INFO_REQUESTED"
EVENT_CITIZEN_INFO_COMPLETED = "CITIZEN_INFO_COMPLETED"
EVENT_ROUTING_CONFIRMED = "ROUTING_CONFIRMED"
EVENT_CASE_ROUTED = "CASE_ROUTED"
EVENT_TASK_CREATED = "TASK_CREATED"
EVENT_TASK_ASSIGNED = "TASK_ASSIGNED"
EVENT_TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"
EVENT_INTERNAL_INFORMATION_REQUESTED = "INTERNAL_INFORMATION_REQUESTED"
EVENT_EXTERNAL_INFORMATION_REQUESTED = "EXTERNAL_INFORMATION_REQUESTED"
EVENT_CASE_STARTED = "CASE_STARTED"
EVENT_DEPARTMENT_ACTION_RECORDED = "DEPARTMENT_ACTION_RECORDED"
EVENT_DRAFT_SAVED = "DRAFT_SAVED"
EVENT_DRAFT_SUBMITTED = "DRAFT_SUBMITTED"
EVENT_DRAFT_APPROVED = "DRAFT_APPROVED"
EVENT_DRAFT_REVISION_REQUESTED = "DRAFT_REVISION_REQUESTED"
EVENT_CASE_COMPLETED = "CASE_COMPLETED"
EVENT_CASE_CLOSED = "CASE_CLOSED"
EVENT_NOTIFICATION_STORED = "NOTIFICATION_STORED"

ACTOR_USER = "USER"
ACTOR_SYSTEM = "SYSTEM"
ACTOR_CITIZEN = "CITIZEN"

TASK_ASSIGNMENT_PENDING = "ASSIGNMENT_PENDING"
TASK_ASSIGNED = "ASSIGNED"
TASK_IN_PROGRESS = "IN_PROGRESS"
TASK_WAITING_INFO = "WAITING_INFO"
TASK_DONE = "DONE"
TASK_STATUSES = frozenset({
    TASK_ASSIGNMENT_PENDING,
    TASK_ASSIGNED,
    TASK_IN_PROGRESS,
    TASK_WAITING_INFO,
    TASK_DONE,
})

DRAFT_TYPES = frozenset(
    {
        "MISSING_INFORMATION_REQUEST",
        "INTERIM_INFORMATION",
        "OFFICIAL_RESPONSE",
        "INTERNAL_MEMO",
        "FORWARDING_COVER_LETTER",
    }
)
DRAFT_STATUS_DRAFT = "DRAFT"
DRAFT_STATUS_EDITED = "EDITED"
DRAFT_STATUS_APPROVED = "APPROVED"
DRAFT_STATUS_SENT = "SENT"
DRAFT_STATUS_CANCELLED = "CANCELLED"

NOTIFICATION_CHANNELS = frozenset({"SMS", "EMAIL", "PORTAL"})

PUBLIC_EVENT_LABELS = {
    EVENT_CASE_RECEIVED: "Evrak alındı",
    EVENT_CITIZEN_INFO_REQUESTED: "Ek bilgi istendi",
    EVENT_CITIZEN_INFO_COMPLETED: "Vatandaş bilgisi alındı",
    EVENT_CASE_ROUTED: "İlgili birime iletildi",
    EVENT_CASE_STARTED: "İşleme alındı",
    EVENT_CASE_COMPLETED: "İşlem tamamlandı",
    EVENT_CASE_CLOSED: "Dosya kapatıldı",
}

PUBLIC_STATUS_LABELS = {
    STATUS_RECEIVED: "Alındı",
    STATUS_ANALYZING: "İnceleniyor",
    STATUS_WAITING_INITIAL_REVIEW: "Ön incelemede",
    STATUS_WAITING_CITIZEN_INFO: "Ek bilgi bekleniyor",
    STATUS_READY_TO_ROUTE: "Yönlendirme bekleniyor",
    STATUS_IN_DEPARTMENT: "Birimde",
    STATUS_IN_PROGRESS: "İşlemde",
    STATUS_RESPONSE_DRAFTED: "Yanıt hazırlanıyor",
    STATUS_WAITING_FINAL_APPROVAL: "Onay bekleniyor",
    STATUS_COMPLETED: "Tamamlandı",
    STATUS_CLOSED: "Kapatıldı",
}
