export type UserRole = "EVRAK_KAYIT" | "BIRIM_PERSONELI";
export type CaseStatus = "RECEIVED" | "ANALYZING" | "WAITING_INITIAL_REVIEW" | "WAITING_CITIZEN_INFO" | "READY_TO_ROUTE" | "IN_DEPARTMENT" | "IN_PROGRESS" | "RESPONSE_DRAFTED" | "WAITING_FINAL_APPROVAL" | "COMPLETED" | "CLOSED";
export type DeadlineRisk = "NORMAL" | "APPROACHING" | "CRITICAL" | "OVERDUE" | "UNKNOWN";
export interface CurrentUser { id: string; name: string; role: UserRole; institution_id: string; department_code: string; department_name?: string }
export interface AuthSession { access_token: string; token_type: "bearer"; user: CurrentUser }
export interface Department { code: string; name: string; responsibility?: string; supported_processes?: string[] }
export interface CaseEvent { id: string; event_type: string; label: string; actor_type?: string; actor_user_id?: string | null; actor_name?: string; created_at: string; from_status?: CaseStatus | null; to_status?: CaseStatus | null; payload?: Record<string, unknown> }
export interface RoutingRecommendation { recommended_unit: string; recommended_department_code: string; score?: number; reason: string; evidence: string[]; alternatives: Array<{ department_code: string; unit: string; reason?: string }>; requires_human_review: boolean }
export interface CaseDeadline { applicable: boolean; deadline_days?: number; deadline_type?: string; due_at?: string | null; remaining_days?: number; risk_level: DeadlineRisk; legal_basis?: { verified: boolean; citation?: string } }
export type ClarificationTargetType = "VATANDAS" | "DIS_KURUM" | "KURUM_ICI" | "INTERNAL_DEPARTMENT";
export interface Clarification { needs_clarification: boolean; blocking: boolean; requested_fields: string[]; question_type: "free_text" | "single_choice"; question: string; options: Array<{ value: string; label: string }>; resume_target: string; reason?: string | null; target_type?: ClarificationTargetType | null; target_name?: string | null; target_department?: string | null; recommended_action?: string | null; required_for_process?: boolean; missing_field?: string | null; draft_available?: boolean }
export interface AiOperation { profile_id?: string | null; task_type?: string | null; recommended_task_type?: string | null; department_code?: string | null; recommended_department?: string | null; team_code?: string | null; recommended_team?: string | null; team_name?: string | null; recommended_role?: string | null; requires_field_visit?: boolean; field_visit_required?: boolean; reason?: string | null; assigned_user_id?: string | null; alternatives?: unknown[]; next_action?: string | null }
export interface PriorityAssessment { priority?: "HIGH" | "MEDIUM" | "LOW" | string; priority_rule?: string; priority_reason?: string; deadline?: string | null; days_remaining?: number | null; decision_source?: string }
export interface CaseAssignment { id: string; case_id: string; department_code: string; assigned_user_id?: string | null; assigned_by_user_id?: string | null; assigned_at: string; ended_at?: string | null; reason?: string | null; routing_snapshot?: Record<string, unknown> }
export type CaseTaskStatus = "ASSIGNMENT_PENDING" | "ASSIGNED" | "IN_PROGRESS" | "WAITING_INFO" | "DONE";
export interface CaseTask { id: string; case_id: string; source_case_id: string; task_type: string; department_code: string; team_code?: string | null; recommended_role?: string | null; assigned_user_id?: string | null; status: CaseTaskStatus; reason?: string | null; ai_recommendation?: AiOperation; created_by_user_id?: string | null; approved_by_user_id?: string | null; created_at: string; updated_at: string }
export interface InformationRequest { id: string; case_id: string; target_type: ClarificationTargetType; target_name?: string | null; target_department?: string | null; requested_fields: string[]; reason: string; recommended_action: string; status: string; created_by_user_id: string; created_at: string }
export interface DepartmentAction { id: string; action_type: string; result: string; decision: string; planned_date?: string | null; notes?: string; verified: boolean; recorded_by_user_id: string; created_at: string }
export interface CaseDraft { id: string; draft_type: "MISSING_INFORMATION_REQUEST" | "INTERIM_INFORMATION" | "OFFICIAL_RESPONSE" | "INTERNAL_MEMO" | "FORWARDING_COVER_LETTER"; draft_status: "DRAFT" | "EDITED" | "APPROVED" | "SENT" | "CANCELLED"; revision?: number; recipient?: string; sender_unit?: string; recipient_kind?: string; subject: string; body: string; prepared_by_department?: string; grounded_action_id?: string | null; created_at?: string; updated_at?: string; ai_generated: boolean }
export interface AnalysisPreviewDraft { analysis_id: string; draft_type: string; subject: string; body: string; recipient?: string | null; recipient_kind?: string | null; edited: boolean }
export interface OfficialWritingListItem extends CaseDraft { case_id: string; tracking_code: string; institution_id: string; originator_name: string; current_department_code: string; current_department_name: string; case_status: CaseStatus; case_version: number }
export interface CaseAnalysisDetails { document?: Record<string, unknown>; extraction?: { fields?: Record<string, { value?: unknown; validated?: boolean }> }; missing_fields?: { missing_fields?: string[]; blocking_fields?: string[] }; legal_analysis?: { verified?: boolean; evidence?: unknown[]; sources?: unknown[]; text?: string }; raw_text?: string }
export interface CaseRecord { id: string; tracking_code: string; analysis_id?: string | null; institution_id: string; title: string; source_type: "VATANDAS" | "DIS_KURUM" | "KURUM_ICI"; source_channel: "WEB_FORM" | "FIZIKI_EVRAK" | "EPOSTA" | "KEP" | "EBYS" | "KURUM_ICI"; originator_type: "VATANDAS" | "DIS_KURUM" | "KURUM_ICI"; originator_name: string; current_department_code: string; current_department_name: string; assigned_user_id?: string | null; workflow_status: CaseStatus; priority?: string | null; received_at: string; created_at: string; updated_at: string; closed_at?: string | null; version: number; routing_recommendation?: RoutingRecommendation; deadline?: CaseDeadline; clarification?: Clarification; ai_operation?: AiOperation; priority_assessment?: PriorityAssessment; assignments?: CaseAssignment[]; tasks?: CaseTask[]; assignment?: CaseTask | null; information_requests?: InformationRequest[]; timeline: CaseEvent[]; department_actions: DepartmentAction[]; drafts: CaseDraft[]; analysis_preview_draft?: AnalysisPreviewDraft | null; analysis_summary?: string; analysis_details?: CaseAnalysisDetails | null; permissions: string[] }
export interface CaseInboxResponse { items: CaseRecord[]; next_cursor: string | null }
export interface PublicCase { tracking_code: string; public_status: string; received_at: string; updated_at: string; timeline: Array<{ event: string; label: string; created_at?: string }>; clarification?: { requested_fields: string[]; question_type: "free_text" | "choice"; question: string; options: Array<{ value: string; label: string }> } | null }
export interface CaseActionResult { case: CaseRecord; message: string }
