export type UserRole = "EVRAK_KAYIT" | "BIRIM_PERSONELI";
export type CaseStatus = "RECEIVED" | "ANALYZING" | "WAITING_INITIAL_REVIEW" | "WAITING_CITIZEN_INFO" | "READY_TO_ROUTE" | "IN_DEPARTMENT" | "IN_PROGRESS" | "RESPONSE_DRAFTED" | "WAITING_FINAL_APPROVAL" | "COMPLETED" | "CLOSED";
export type DeadlineRisk = "NORMAL" | "APPROACHING" | "CRITICAL" | "OVERDUE" | "UNKNOWN";
export interface CurrentUser { id: string; name: string; role: UserRole; institution_id: string; department_code: string; department_name?: string }
export interface AuthSession { access_token: string; token_type: "bearer"; user: CurrentUser }
export interface Department { code: string; name: string; responsibility?: string; supported_processes?: string[] }
export interface CaseEvent { id: string; event_type: string; label: string; actor_name?: string; created_at: string; from_status?: CaseStatus | null; to_status?: CaseStatus | null }
export interface RoutingRecommendation { recommended_unit: string; recommended_department_code: string; score?: number; reason: string; evidence: string[]; alternatives: Array<{ department_code: string; unit: string; reason?: string }>; requires_human_review: boolean }
export interface CaseDeadline { applicable: boolean; deadline_days?: number; deadline_type?: string; due_at?: string | null; remaining_days?: number; risk_level: DeadlineRisk; legal_basis?: { verified: boolean; citation?: string } }
export interface Clarification { needs_clarification: boolean; blocking: boolean; requested_fields: string[]; question_type: "free_text" | "single_choice"; question: string; options: Array<{ value: string; label: string }>; resume_target: string }
export interface DepartmentAction { id: string; action_type: string; result: string; decision: string; planned_date?: string | null; notes?: string; verified: boolean; recorded_by_user_id: string; created_at: string }
export interface CaseDraft { id: string; draft_type: "MISSING_INFORMATION_REQUEST" | "INTERIM_INFORMATION" | "OFFICIAL_RESPONSE" | "INTERNAL_MEMO" | "FORWARDING_COVER_LETTER"; draft_status: "DRAFT" | "EDITED" | "APPROVED" | "SENT" | "CANCELLED"; recipient?: string; subject: string; body: string; prepared_by_department?: string; ai_generated: boolean }
export interface CaseRecord { id: string; tracking_code: string; analysis_id?: string | null; institution_id: string; title: string; source_type: "VATANDAS" | "DIS_KURUM" | "KURUM_ICI"; source_channel: "WEB_FORM" | "FIZIKI_EVRAK" | "EPOSTA" | "KEP" | "EBYS" | "KURUM_ICI"; originator_type: "VATANDAS" | "DIS_KURUM" | "KURUM_ICI"; originator_name: string; current_department_code: string; current_department_name: string; assigned_user_id?: string | null; workflow_status: CaseStatus; priority?: string | null; received_at: string; created_at: string; updated_at: string; closed_at?: string | null; version: number; routing_recommendation?: RoutingRecommendation; deadline?: CaseDeadline; clarification?: Clarification; timeline: CaseEvent[]; department_actions: DepartmentAction[]; drafts: CaseDraft[]; analysis_summary?: string; permissions: string[] }
export interface CaseInboxResponse { items: CaseRecord[]; next_cursor: string | null }
export interface PublicCase { tracking_code: string; public_status: string; received_at: string; updated_at: string; timeline: Array<{ event: string; label: string; created_at?: string }>; clarification?: { requested_fields: string[]; question_type: "free_text" | "choice"; question: string; options: Array<{ value: string; label: string }> } | null }
export interface CaseActionResult { case: CaseRecord; message: string }
