import React, { useCallback, useEffect, useState } from "react";
import { Activity, Bot, Building2, CheckCircle2, Cpu, Database, RefreshCw, Server, ShieldCheck, Workflow } from "lucide-react";
import type { EvaluationSummary, InstitutionOption, SystemStatus } from "../services/api";
import { api } from "../services/api";
import "./ai-operations.css";

interface Props { institution: InstitutionOption | null; onOpenAnalysis: (analysisId: string) => void | Promise<void> }
interface ReadyState { ready?: boolean; services?: Record<string, { status?: string; provider?: string; message?: string }>; message?: string }
const agents = [
  ["Document Agent", "Belge sınıflandırma ve süreç amacı"], ["Extraction Agent", "Doğrulanabilir alan çıkarımı"], ["Legal Agent", "Kanıt temelli mevzuat erişimi"], ["Missing Field Agent", "Bloke edici eksik bilgi"], ["Summary Agent", "Karar destek özeti"], ["Routing Agent", "Kurum profiline bağlı birim önerisi"], ["Writing Agent", "Doğrulanmış işlemden resmî taslak"], ["Quality Agent", "Biçim ve güvenlik kontrolü"],
];

export const AIOperationsPage: React.FC<Props> = ({ institution }) => {
  const [ready, setReady] = useState<ReadyState>(); const [system, setSystem] = useState<SystemStatus>(); const [evaluation, setEvaluation] = useState<EvaluationSummary>(); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const results = await Promise.allSettled([api.checkSystemReady(), api.getSystemStatus(), api.getEvaluationSummary()]); if (results[0].status === "fulfilled") setReady(results[0].value); if (results[1].status === "fulfilled") setSystem(results[1].value); if (results[2].status === "fulfilled") setEvaluation(results[2].value); if (results.every((x) => x.status === "rejected")) setError("Sistem gözlemlenebilirlik servislerine erişilemedi."); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const service = (key: string) => ready?.services?.[key]?.status === "ok";
  return <div className="aiops-page"><header className="aiops-hero"><div><span className="section-kicker">TEKNİK GÖZLEMLENEBİLİRLİK</span><h1>AI Operasyonları</h1><p>Sistem hazırlığı, ajan mimarisi, model sağlayıcıları ve offline değerlendirme. Vaka ve taslak işlemleri Case Workspace’te yürütülür.</p></div><button className="btn btn-secondary" disabled={loading} onClick={() => void load()}><RefreshCw size={16}/> Yenile</button></header>{error && <div className="case-error">{error}</div>}<section className="aiops-status-grid"><Status icon={<Server/>} label="Backend" value={ready?.ready ? "Hazır" : "Kontrol gerekli"} ok={Boolean(ready?.ready)}/><Status icon={<Bot/>} label="LLM" value={system?.llm_provider || ready?.services?.llm?.provider || "Bilinmiyor"} detail={system?.llm_model} ok={service("llm")}/><Status icon={<Database/>} label="Qdrant / RAG" value={system?.qdrant?.index_status || (service("qdrant") ? "Hazır" : "Kontrol gerekli")} detail={system?.qdrant?.legal_points !== undefined ? `${system.qdrant.legal_points} mevzuat noktası` : undefined} ok={service("qdrant")}/><Status icon={<Cpu/>} label="Embedding" value={system?.embedding_model || "Bilinmiyor"} detail={system?.embedding_dimension ? `${system.embedding_dimension} boyut` : undefined} ok={service("embedding")}/><Status icon={<Building2/>} label="Aktif kurum" value={institution?.label || "Seçilmedi"} ok={Boolean(institution)}/></section><section className="aiops-panel"><div className="aiops-section-title"><Workflow/><div><span>AJAN PIPELINE</span><h2>EVRAG karar destek mimarisi</h2></div></div><div className="aiops-agent-grid">{agents.map(([name, task]) => <article className="aiops-agent-card" key={name}><span className="aiops-agent-icon"><CheckCircle2/></span><h3>{name}</h3><p>{task}</p><small>Case-aware · insan denetimli</small></article>)}</div></section><div className="aiops-secondary-grid"><section className="aiops-panel"><div className="aiops-section-title"><ShieldCheck/><div><span>DEĞERLENDİRME</span><h2>Offline kalite kapısı</h2></div></div><p>{evaluation?.available ? "Son değerlendirme artifact’i erişilebilir." : evaluation?.message || "Tamamlanmış değerlendirme artifact’i bulunmuyor."}</p><small>Bu ekran model veya benchmark çalıştırmaz; yalnız mevcut artifact’i raporlar.</small></section><section className="aiops-panel"><div className="aiops-section-title"><Activity/><div><span>ÇALIŞMA KAYITLARI</span><h2>Vaka merkezli izlenebilirlik</h2></div></div><p>Sonuç, karar izi ve süreler ilgili dosyanın zaman çizelgesinde tutulur.</p><p>Operasyonel dosyalar için <b>Dosyalar → Case Workspace</b> yolunu kullanın.</p></section></div></div>;
};

function Status({ icon, label, value, detail, ok }: { icon: React.ReactNode; label: string; value: string; detail?: string; ok: boolean }) { return <article className={`aiops-status-card ${ok ? "ok" : "warning"}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong>{detail && <em>{detail}</em>}</div></article>; }
