import React, { useEffect, useState } from "react";
import { ArrowRight, CalendarClock, FileSearch, UserRound } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";
import { caseApi } from "../services/caseApi";
import type { CaseRecord } from "../types/case";
import { EmptyState, StatusBadge } from "../components/case/CasePrimitives";
const source = { VATANDAS: "Vatandaş", DIS_KURUM: "Dış Kurum", KURUM_ICI: "Kurum İçi" };
export function CaseInboxPage({ history = false }: { history?: boolean }) { const { token, user } = useAuth(); const [params] = useSearchParams(); const [items, setItems] = useState<CaseRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { if (!token) return; const query = history ? "scope=history" : params.toString(); setLoading(true); setError(""); void caseApi.inbox(token, query).then((x) => setItems(x.items)).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, [token, params, history]); return <div className="case-page"><header className="case-page-heading"><div><span className="eyebrow">{user?.role === "EVRAK_KAYIT" ? "KURUM EVRAK HAVUZU" : user?.department_name?.toUpperCase()}</span><h1>{history ? "İşlem Geçmişi" : user?.role === "EVRAK_KAYIT" ? "Gelen Evrak Havuzu" : "Birim Dosyaları"}</h1><p>{history ? "Havale edilmiş dosyalar dahil kurumun işlem ve denetim geçmişi." : "Liste backend tarafından kurum, rol ve birim yetkinize göre filtrelenir."}</p></div></header>{error && <div className="case-error" role="alert">{error}</div>}{loading ? <div className="case-loading">Dosyalar yükleniyor…</div> : error ? null : items.length === 0 ? <EmptyState title="Bu görünümde dosya yok" text="Filtreye ve yetki kapsamınıza uygun bir kayıt bulunamadı."/> : <section className="case-card-grid">{items.map((item) => <article className="case-card" key={item.id}><header><span>{item.tracking_code}</span><StatusBadge status={item.workflow_status}/></header><h2>{item.title}</h2><dl><div><dt><UserRound/> Kaynak</dt><dd>{source[item.source_type]} · {item.source_channel}</dd></div><div><dt>Başvuru sahibi</dt><dd>{item.originator_name}</dd></div><div><dt>Gerçek sahip</dt><dd>{item.current_department_name}</dd></div>{item.routing_recommendation && <div className="ai-recommendation-row"><dt>AI Önerisi</dt><dd>{item.routing_recommendation.recommended_unit}</dd></div>}<div><dt><CalendarClock/> Alınma</dt><dd>{new Date(item.received_at).toLocaleDateString("tr-TR")}</dd></div>{item.deadline?.applicable && item.deadline.legal_basis?.verified && <div><dt>Yasal süre</dt><dd>{item.deadline.deadline_days} gün · {item.deadline.risk_level}</dd></div>}</dl><Link to={`/dosya/${item.id}`}>Dosyayı aç <ArrowRight size={16}/></Link></article>)}</section>}</div>; }
