import React, { useEffect, useState } from "react";
import { ArrowRight, Building2, Search, ShieldCheck, UserRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { EVRAGBrand } from "../components/EVRAGBrand";
import { useAuth } from "../contexts/AuthContext";
import { demoApi, type DemoPersona } from "../services/demoApi";

const citizenExamples = [
  ["yol_onarim", "Yol Onarım Başvurusunu Görüntüle"],
  ["eksik_adres", "Bilgi Bekleyen Başvuruyu Görüntüle"],
  ["tamamlanmis_dosya", "Sonuçlanmış Başvuruyu Görüntüle"],
] as const;
export function DemoLoginPage() {
  const { login } = useAuth(); const navigate = useNavigate();
  const [personas, setPersonas] = useState<DemoPersona[]>([]); const [trackingCode, setTrackingCode] = useState(""); const [accessKey, setAccessKey] = useState(""); const [busy, setBusy] = useState<string>(); const [error, setError] = useState("");
  useEffect(() => { void demoApi.personas().then((result) => setPersonas(result.items)).catch((cause) => setError(cause.message)); }, []);
  async function select(key: string) { setBusy(key); setError(""); try { await login(key); } catch (cause) { setError(cause instanceof Error ? cause.message : "Demo oturumu başlatılamadı."); } finally { setBusy(undefined); } }
  function submitCitizen(event: React.FormEvent) { event.preventDefault(); const code = trackingCode.trim(); const token = accessKey.trim(); if (!code || !token) return setError("Takip numarası ve erişim anahtarı gereklidir."); navigate(`/takip/${encodeURIComponent(code)}?token=${encodeURIComponent(token)}`); }
  async function openExample(key: string) { setBusy(key); setError(""); try { const result = await demoApi.prepareCitizenExample(key); navigate(result.citizen_url); } catch (cause) { setError(cause instanceof Error ? cause.message : "Örnek başvuru açılamadı."); } finally { setBusy(undefined); } }
  return <main className="role-login"><section className="role-login-hero"><EVRAGBrand variant="full" theme="dark"/><span className="eyebrow">KURUMSAL İŞ AKIŞI</span><h1>Doğru rol, doğru dosya,<br/>insan denetiminde yapay zekâ.</h1><p>EVRAG, kamu evrakını güvenli insan kararlarıyla uçtan uca yöneten karar destek katmanıdır.</p><div className="trust-line"><ShieldCheck size={18}/> Yapay zekâ önerir, kurum personeli karar verir.</div></section><section className="role-login-panel"><div><span className="eyebrow">KURUM PERSONELİ</span><h2>Demo rolünü seçin</h2><p>Kimlik, kurum ve birim yetkisi backend tarafından doğrulanır.</p></div><div className="persona-list">{personas.map((person) => <button key={person.user_key} className="persona-card" disabled={Boolean(busy)} onClick={() => void select(person.user_key)}><span className="persona-icon"><UserRound/></span><span className="persona-copy"><strong>{person.name}</strong><small><Building2 size={14}/> {person.institution_id === "belediye" ? "Belediye" : "Kaymakamlık"}</small><b>{person.role === "EVRAK_KAYIT" ? "Evrak Kayıt Personeli" : "Birim Personeli"}</b></span><ArrowRight className="persona-arrow"/></button>)}</div><section className="citizen-entry"><span className="eyebrow">VATANDAŞ BAŞVURU TAKİBİ</span><h2>Başvurunuzun durumunu görüntüleyin</h2><p>Vatandaş erişimi kurum personeli oturumundan bağımsızdır.</p><form onSubmit={submitCitizen}><label>Takip Numarası<input value={trackingCode} onChange={(event) => setTrackingCode(event.target.value)} placeholder="EVR-2026-00001"/></label><label>Erişim Anahtarı<input value={accessKey} onChange={(event) => setAccessKey(event.target.value)} type="password"/></label><button className="btn btn-primary"><Search size={16}/> Başvurumu Görüntüle</button></form><div className="citizen-examples"><strong>ÖRNEK BAŞVURULAR</strong>{citizenExamples.map(([key, label]) => <button key={key} disabled={Boolean(busy)} onClick={() => void openExample(key)}>{busy === key ? "Hazırlanıyor…" : label}<ArrowRight size={15}/></button>)}</div></section>{error && <div className="case-error" role="alert">{error}</div>}</section></main>;
}