import React, { useEffect, useMemo, useState } from "react";
import { FileText, Search } from "lucide-react";
import { Link } from "react-router-dom";
import { OfficialWritingWorkspace } from "../components/case/OfficialWritingWorkspace";
import { useAuth } from "../contexts/AuthContext";
import { caseApi } from "../services/caseApi";
import type { CaseRecord, OfficialWritingListItem } from "../types/case";

const filters = [["ALL", "Tümü"], ["DRAFT", "Taslak"], ["EDITED", "Düzenleme Bekliyor"], ["WAITING", "Onay Bekliyor"], ["APPROVED", "Onaylandı"]] as const;
export function OfficialWritingsPage() { const { token } = useAuth(); const [items, setItems] = useState<OfficialWritingListItem[]>([]); const [filter, setFilter] = useState("ALL"); const [query, setQuery] = useState(""); const [selectedCase, setSelectedCase] = useState<CaseRecord>(); const [error, setError] = useState(""); const load = () => token ? caseApi.officialWritings(token).then((x) => setItems(x.items)).catch((e) => setError(e.message)) : Promise.resolve(); useEffect(() => { void load(); }, [token]); const shown = useMemo(() => items.filter((x) => (filter === "ALL" || (filter === "WAITING" ? x.draft_status !== "APPROVED" : x.draft_status === filter)) && `${x.tracking_code} ${x.subject} ${x.recipient}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))), [items, filter, query]); async function open(item: OfficialWritingListItem) { if (token) setSelectedCase(await caseApi.get(token, item.case_id)); } return <div className="case-page official-center"><header className="case-page-heading"><div><span className="eyebrow">KURUMSAL BELGE YÖNETİMİ</span><h1>Giden Evraklar</h1><p>Yetkili olduğunuz vakalardaki iç yazışmalar, resmî cevaplar, sürümler ve onaylar.</p></div></header><div className="writing-toolbar"><div>{filters.map(([key, label]) => <button className={filter === key ? "active" : ""} onClick={() => setFilter(key)} key={key}>{label}</button>)}</div><label><Search/><input placeholder="Takip kodu, konu veya muhatap" value={query} onChange={(e) => setQuery(e.target.value)}/></label></div>{error && <div className="case-error">{error}</div>}<div className="official-center-grid"><section className="writing-card-list">{shown.map((item) => <article key={item.id}><span><FileText/></span><div><small>{item.tracking_code} · {item.current_department_name}</small><h2>{item.subject}</h2><p>{item.sender_unit || item.current_department_name} → {item.recipient || item.originator_name}</p><em>{item.draft_type.replaceAll("_", " ")} · v{item.revision || 1} · {item.draft_status}</em></div><div><button className="btn btn-secondary" onClick={() => void open(item)}>Görüntüle</button><Link className="btn btn-secondary" to={`/dosya/${item.case_id}`}>Case’i Aç</Link></div></article>)}{!error && shown.length === 0 && <p className="case-empty">Bu filtrede giden evrak bulunmuyor.</p>}</section>{selectedCase && token && <OfficialWritingWorkspace item={selectedCase} token={token} onRefresh={async () => { setSelectedCase(await caseApi.get(token, selectedCase.id)); await load(); }} onNotice={() => undefined}/>}</div></div>; }
