import React from "react";
import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { CaseProductPanels } from "../components/case/CaseProductPanels";
import type { CaseRecord } from "../types/case";

const base: CaseRecord = { id: "case-1", tracking_code: "EVR-1", institution_id: "belediye", title: "Yol bakım", source_type: "VATANDAS", source_channel: "WEB_FORM", originator_type: "VATANDAS", originator_name: "Ali Yılmaz", current_department_code: "fen_isleri", current_department_name: "Fen İşleri Müdürlüğü", workflow_status: "IN_PROGRESS", received_at: "2026-01-01", created_at: "2026-01-01", updated_at: "2026-01-01", version: 3, timeline: [], department_actions: [], drafts: [], permissions: ["RECORD_DEPARTMENT_ACTION", "SAVE_DRAFT"], analysis_summary: "Yol bakım talebi", analysis_details: { document: { document_type: "dilekçe", process_intent: "bildirim" }, extraction: { fields: { location: { value: "Çınar Sokak", validated: true } } }, missing_fields: { missing_fields: [] }, legal_analysis: { verified: true, text: "3071 sayılı Kanun" } } };

describe("Case official writing and report experience", () => {
  it("always exposes the reply-draft area and locked flow before DepartmentAction", () => { render(<CaseProductPanels item={base} token="token" onRefresh={vi.fn()} onNotice={vi.fn()}/>); fireEvent.click(screen.getByRole("button", { name: /Cevap Taslağı/ })); expect(screen.getByText("Cevap taslağı alanı hazır")).toBeInTheDocument(); expect(screen.getByText(/Kurum İşlemi → Taslak/)).toBeInTheDocument(); });
  it("uses the requested tab order and shows all AI detail sections", () => { render(<CaseProductPanels item={base} token="token" onRefresh={vi.fn()} onNotice={vi.fn()}/>); const tabs = screen.getByRole("navigation", { name: "Dosya çalışma alanı bölümleri" }).querySelectorAll("button"); expect(Array.from(tabs).map((tab) => tab.textContent)).toEqual(["Genel Bakış", "Cevap Taslağı", "İşlem Geçmişi", "Teknik AI Detayı"]); fireEvent.click(screen.getByRole("button", { name: "Teknik AI Detayı" })); for (const label of ["Belge", "Özet", "Çıkarılan Bilgiler", "Eksik Bilgiler", "Mevzuat / Kanıt", "Yönlendirme", "Resmî Yazışma Kontrolleri"]) expect(screen.getAllByText(label).length).toBeGreaterThan(0); });
  it("separates preview and edit while exposing permission-backed approval", () => { const item = { ...base, workflow_status: "RESPONSE_DRAFTED" as const, department_actions: [{ id: "a", action_type: "İNCELEME", result: "Tespit", decision: "Programa alındı", verified: true, recorded_by_user_id: "u", created_at: "2026-01-01" }], permissions: ["SAVE_DRAFT", "APPROVE_DRAFT"], drafts: [{ id: "d", draft_type: "OFFICIAL_RESPONSE" as const, draft_status: "DRAFT" as const, revision: 1, recipient: "Ali Yılmaz", subject: "Başvurunuz Hk.", body: "Başvurunuz incelenmiştir.", grounded_action_id: "a", ai_generated: true }] }; render(<CaseProductPanels item={item} token="token" onRefresh={vi.fn()} onNotice={vi.fn()}/>); fireEvent.click(screen.getByRole("button", { name: /Cevap Taslağı/ })); expect(screen.queryByText("T.C.")).not.toBeInTheDocument(); expect(screen.getByRole("button", { name: "Taslağı Düzenle" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Onayla" })).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Taslağı Önizle" })); expect(screen.getByText("T.C.")).toBeInTheDocument(); expect(screen.getByText("Kalite Kontrolü")).toBeInTheDocument(); });
  it("does not expose final approval without backend permission", () => { const item = { ...base, workflow_status: "RESPONSE_DRAFTED" as const, permissions: ["SAVE_DRAFT"], drafts: [{ id: "d", draft_type: "OFFICIAL_RESPONSE" as const, draft_status: "EDITED" as const, subject: "Yanıt", body: "İncelendi.", ai_generated: true }] }; render(<CaseProductPanels item={item} token="token" onRefresh={vi.fn()} onNotice={vi.fn()}/>); fireEvent.click(screen.getByRole("button", { name: /Cevap Taslağı/ })); expect(screen.getByRole("button", { name: "Taslağı Düzenle" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Onayla" })).not.toBeInTheDocument(); });
});
