import React, { useState } from "react";
import { CheckCircle2, Download, ExternalLink, QrCode } from "lucide-react";
import type { CaseRecord } from "../../types/case";
import { caseApi } from "../../services/caseApi";
import { caseDownload } from "../../services/caseHttp";
import { demoApi } from "../../services/demoApi";

const stages = ["Alındı", "AI Analizi", "İlk İnceleme", "Yönlendirme", "Birim İşlemi", "Cevap", "Onay", "Tamamlandı"];
const rank: Record<string, number> = { RECEIVED: 0, ANALYZING: 1, WAITING_INITIAL_REVIEW: 2, WAITING_CITIZEN_INFO: 2, READY_TO_ROUTE: 3, IN_DEPARTMENT: 3, IN_PROGRESS: 4, RESPONSE_DRAFTED: 5, WAITING_FINAL_APPROVAL: 6, COMPLETED: 7, CLOSED: 7 };

export function CaseProductPanels({ item, token, onRefresh, onNotice }: { item: CaseRecord; token: string; onRefresh: () => Promise<void>; onNotice: (text: string) => void }) {
  const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const analysis = item.analysis_details; const fields = Object.entries(analysis?.extraction?.fields || {}).filter(([, value]) => value?.value != null); const missing = analysis?.missing_fields?.missing_fields || []; const latest = [...item.drafts].reverse().find((draft) => draft.draft_type === "OFFICIAL_RESPONSE");
  async function approve() { if (!latest) return; setBusy("approve"); try { await caseApi.approveDraft(token, item, latest.id); await onRefresh(); onNotice("Resmî cevap taslağı insan onayıyla doğrulandı."); } catch (e) { setError(e instanceof Error ? e.message : "Taslak onaylanamadı."); } finally { setBusy(""); } }
  async function download(format: "docx" | "pdf") { if (!latest) return; setBusy(format); try { await caseDownload(`/api/cases/${item.id}/drafts/${latest.id}/export/${format}`, token, `${item.tracking_code}.${format}`); } catch (e) { setError(e instanceof Error ? e.message : "Belge indirilemedi."); } finally { setBusy(""); } }
  async function citizen() { setBusy("citizen"); try { const access = await demoApi.citizenAccess(token, item.id); window.open(access.citizen_url, "_blank", "noopener,noreferrer"); } catch (e) { setError(e instanceof Error ? e.message : "Bu dosya için demo vatandaş bağlantısı yok."); } finally { setBusy(""); } }
  return <>
    <section className="case-panel workflow-stepper"><span className="eyebrow">UÇTAN UCA İŞ AKIŞI</span><div>{stages.map((stage, index) => <span className={index <= (rank[item.workflow_status] ?? 0) ? "done" : ""} key={stage}><i>{index < (rank[item.workflow_status] ?? 0) ? "✓" : index + 1}</i>{stage}</span>)}</div></section>
    <section className="case-panel"><span className="eyebrow">GÖREV 1 · BELGE VE İÇERİK ANALİZİ</span><h2>AI ön inceleme</h2><div className="analysis-fact-grid"><article><small>Belge türü</small><strong>{String(analysis?.document?.document_type || "—")}</strong></article><article><small>Süreç amacı</small><strong>{String(analysis?.document?.process_intent || "—")}</strong></article><article><small>Çıkarılan bilgiler</small>{fields.length ? fields.map(([key, value]) => <p key={key}><b>{key.replaceAll("_", " ")}:</b> {String(value.value)}</p>) : <p>Doğrulanmış alan yok.</p>}</article><article><small>Eksik bilgiler</small><strong>{missing.length ? missing.join(", ") : "Bloke edici eksik yok"}</strong></article><article className="full"><small>Mevzuat / kanıt</small><p>{analysis?.legal_analysis?.text || (analysis?.legal_analysis?.verified ? "Doğrulanmış mevzuat kanıtı mevcut." : "Doğrulanmış özel mevzuat kanıtı bulunamadı; genel süreç kuralları uygulanır.")}</p></article></div></section>
    {latest && <section className="case-panel official-case-draft"><header><div><span className="eyebrow">GÖREV 2 · RESMÎ CEVAP</span><h2>Resmî Yazı Taslağı</h2></div><span className={`draft-status ${latest.draft_status.toLowerCase()}`}>{latest.draft_status === "APPROVED" ? "İnsan onaylı" : "Taslak · onay bekliyor"}</span></header><div className="case-a4"><p className="center"><b>T.C.<br/>{item.institution_id === "belediye" ? "BELEDİYE BAŞKANLIĞI" : "KAYMAKAMLIK"}<br/>{item.current_department_name}</b></p><p><b>Sayı:</b> [EBYS SAYISI] <span><b>Tarih:</b> {new Date().toLocaleDateString("tr-TR")}</span></p><p><b>Konu:</b> {latest.subject}</p><p className="center"><b>{latest.recipient || item.originator_name}</b></p>{latest.body.split("\n").map((line, index) => <p key={index}>{line}</p>)}<div className="case-qr"><QrCode/><small>{item.tracking_code}<br/>EVRAG doğrulama kaydı</small></div></div><div className="draft-actions">{latest.draft_status !== "APPROVED" && <button className="btn btn-primary" disabled={Boolean(busy)} onClick={() => void approve()}><CheckCircle2 size={16}/> Taslağı Onayla</button>}<button className="btn btn-secondary" disabled={latest.draft_status !== "APPROVED" || Boolean(busy)} onClick={() => void download("docx")}><Download size={16}/> DOCX</button><button className="btn btn-secondary" disabled={latest.draft_status !== "APPROVED" || Boolean(busy)} onClick={() => void download("pdf")}><Download size={16}/> PDF</button><button className="btn btn-secondary" disabled={Boolean(busy)} onClick={() => void citizen()}><ExternalLink size={16}/> Vatandaş görünümü</button></div>{error && <div className="case-error">{error}</div>}</section>}
  </>;
}
