import React, { useState } from "react";
import { BookOpen, CheckCircle2, FileSearch, History, Route, ShieldCheck } from "lucide-react";
import type { CaseRecord } from "../../types/case";
import { CaseTimeline } from "./CasePrimitives";
import { OfficialWritingWorkspace } from "./OfficialWritingWorkspace";

const stages = ["Alındı", "AI Analizi", "İlk İnceleme", "Yönlendirme", "Birim İşlemi", "Cevap", "Onay", "Tamamlandı"];
const rank: Record<string, number> = { RECEIVED: 0, ANALYZING: 1, WAITING_INITIAL_REVIEW: 2, WAITING_CITIZEN_INFO: 2, READY_TO_ROUTE: 3, IN_DEPARTMENT: 3, IN_PROGRESS: 4, RESPONSE_DRAFTED: 5, WAITING_FINAL_APPROVAL: 6, COMPLETED: 7, CLOSED: 7 };
type Tab = "overview" | "report" | "writings" | "timeline";
export function CaseProductPanels({ item, token, onRefresh, onNotice }: { item: CaseRecord; token: string; onRefresh: () => Promise<void>; onNotice: (text: string) => void }) { const [tab, setTab] = useState<Tab>("overview"); const analysis = item.analysis_details; const fields = Object.entries(analysis?.extraction?.fields || {}).filter(([, value]) => value?.value != null); const missing = analysis?.missing_fields?.missing_fields || []; const legal = analysis?.legal_analysis;
  return <><section className="case-panel workflow-stepper"><span className="eyebrow">UÇTAN UCA İŞ AKIŞI</span><div>{stages.map((stage, index) => <span className={index <= (rank[item.workflow_status] ?? 0) ? "done" : ""} key={stage}><i>{index < (rank[item.workflow_status] ?? 0) ? "✓" : index + 1}</i>{stage}</span>)}</div></section><nav className="case-workspace-tabs" aria-label="Dosya çalışma alanı bölümleri"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Genel Bakış</button><button className={tab === "report" ? "active" : ""} onClick={() => setTab("report")}>AI Analiz Raporu</button><button className={tab === "writings" ? "active" : ""} onClick={() => setTab("writings")}>Cevap Taslağı ({item.drafts.length})</button><button className={tab === "timeline" ? "active" : ""} onClick={() => setTab("timeline")}>İşlem Geçmişi</button></nav>
    {tab === "overview" && <section className="case-panel report-overview"><span className="eyebrow">DOSYA ÖZETİ</span><h2>{item.analysis_summary || item.title}</h2><div className="analysis-fact-grid"><article><small>Belge türü</small><strong>{String(analysis?.document?.document_type || "—")}</strong></article><article><small>Süreç amacı</small><strong>{String(analysis?.document?.process_intent || "—")}</strong></article><article><small>Mevcut sahip</small><strong>{item.current_department_name}</strong></article><article><small>Durum</small><strong>{item.workflow_status.replaceAll("_", " ")}</strong></article></div></section>}
    {tab === "report" && <section className="case-panel ai-report-view"><header><div><span className="eyebrow">TEKNOFEST GÖREV 1</span><h2><FileSearch/> AI Analiz Raporu</h2><p>Yapay zekânın belge üzerinde bulduğu karar destek sonuçlarının tek görünümü.</p></div></header><div className="report-section-grid"><article><h3>Belge</h3><p><b>Tür:</b> {String(analysis?.document?.document_type || "—")}</p><p><b>Süreç amacı:</b> {String(analysis?.document?.process_intent || "—")}</p></article><article><h3>Özet</h3><p>{item.analysis_summary || "Özet bulunmuyor."}</p></article><article><h3>Çıkarılan Bilgiler</h3>{fields.length ? fields.map(([key, value]) => <p key={key}><b>{key.replaceAll("_", " ")}:</b> {String(value.value)}</p>) : <p>Doğrulanmış alan yok.</p>}</article><article><h3>Eksik Bilgiler</h3><p>{missing.length ? missing.join(", ") : "Bloke edici eksik bilgi yok."}</p></article><article><h3><BookOpen/> Mevzuat / Kanıt</h3><p>{legal?.text || (legal?.verified ? "Doğrulanmış mevzuat kanıtı mevcut." : "Doğrulanmış özel mevzuat kanıtı bulunamadı.")}</p></article><article><h3><Route/> Yönlendirme</h3><p><b>Öneri:</b> {item.routing_recommendation?.recommended_unit || "—"}</p><p>{item.routing_recommendation?.reason}</p>{item.routing_recommendation?.alternatives?.length ? <p><b>Alternatif:</b> {item.routing_recommendation.alternatives.map((x) => x.unit).join(", ")}</p> : null}</article><article className="full"><h3><ShieldCheck/> Resmî Yazışma Kontrolleri</h3><div className="report-checks"><span><CheckCircle2/> Muhatap doğruluğu</span><span><CheckCircle2/> Resmî üslup ve yapı</span><span><CheckCircle2/> Kurum işlem sonucu ile uyum</span><span><CheckCircle2/> Desteksiz işlem iddiası kontrolü</span></div></article></div></section>}
    {tab === "writings" && <OfficialWritingWorkspace item={item} token={token} onRefresh={onRefresh} onNotice={onNotice}/>} {tab === "timeline" && <section className="case-panel"><h2><History/> İşlem Geçmişi</h2><CaseTimeline events={item.timeline}/></section>}
  </>;
}
